// @vitest-environment node
import { describe, it, expect, vi, afterEach } from "vitest";
import { handleRequest } from "../../api/contact";
const valid={form:"contact",name:"Test Customer",phone:"6625550123",email:"customer@example.com",contactMethod:"email",serviceType:"Plumbing",message:"Test only"};
function request(body: unknown=valid, origin="https://weathersair.com") { return new Request("https://weathersair.com/api/contact",{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify(body)}); }
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
describe("secure contact endpoint",()=>{
  it("rejects another origin without calling Resend",async()=>{const send=vi.spyOn(globalThis,"fetch");expect((await handleRequest(request(valid,"https://unrelated.example"))).status).toBe(403);expect(send).not.toHaveBeenCalled();});
  it.each([{name:""},{email:"bad"},{phone:"123"},{contactMethod:"email",email:""},{company:"spam"},{message:"x".repeat(5001)}])("rejects invalid request fields: %j",async(change)=>{const send=vi.spyOn(globalThis,"fetch");expect((await handleRequest(request({...valid,...change}))).status).toBe(400);expect(send).not.toHaveBeenCalled();});
  it("fails truthfully when not configured",async()=>{vi.stubEnv("RESEND_API_KEY","");expect((await handleRequest(request())).status).toBe(503);});
  it("locks sender and recipient while preserving reply-to",async()=>{vi.stubEnv("RESEND_API_KEY","test-key");const send=vi.spyOn(globalThis,"fetch").mockResolvedValue(Response.json({id:"test-id"}));const response=await handleRequest(request({...valid,to:"attacker@example.com",from:"attacker@example.com"}));expect(response.status).toBe(200);expect((await response.json()).success).toBe(true);const payload=JSON.parse(send.mock.calls[0][1]?.body as string);expect(payload.to).toEqual(["mary@weathersairconditioning.com"]);expect(payload.from).toBe("Weathers Air Conditioning <support@team.weathersair.com>");expect(payload.reply_to).toBe("customer@example.com");expect(send.mock.calls[0][1]?.headers).toMatchObject({"Idempotency-Key":expect.stringMatching(/^website-/)});});
  it("does not claim success on provider rejection",async()=>{vi.stubEnv("RESEND_API_KEY","test-key");vi.spyOn(globalThis,"fetch").mockResolvedValue(Response.json({message:"internal provider detail"},{status:403}));const r=await handleRequest(request());expect(r.status).toBe(502);expect(JSON.stringify(await r.json())).not.toContain("internal provider detail");});
  it("notifies Mary of newsletter requests without claiming enrollment",async()=>{vi.stubEnv("RESEND_API_KEY","test-key");const send=vi.spyOn(globalThis,"fetch").mockResolvedValue(Response.json({id:"test-id"}));expect((await handleRequest(request({form:"newsletter",email:"customer@example.com"}))).status).toBe(200);expect(JSON.parse(send.mock.calls[0][1]?.body as string).text).toContain("not automatic mailing-list enrollment");});
});
