import { Link } from "react-router-dom";
import { Building2, ShieldCheck, ClipboardList, Phone } from "lucide-react";
import Seo from "@/components/Seo";
import PageHero from "@/components/PageHero";
import { BUSINESS } from "@/lib/business";
import { breadcrumbSchema } from "@/lib/schema";

const capabilities = [
  { title: "HVAC service & troubleshooting", text: "Discuss equipment symptoms, affected areas and the level of disruption before defining a diagnostic visit. Identify access restrictions and who can authorize work." },
  { title: "Preventive maintenance", text: "Build the conversation around an equipment inventory, visit frequency, documented tasks and reporting needs. Confirm repairs and materials that fall outside the maintenance scope." },
  { title: "Installation & replacement", text: "Review equipment requirements, existing connections, site access and allowable shutdown windows. Define installation, startup and closeout expectations in the project scope." },
];
export default function FederalHVAC() {
  const path = "/federal-hvac-contracting";
  return <>
    <Seo title="Federal HVAC Contractor | Weathers Air Conditioning" description="Weathers is a Columbus, MS federal HVAC contractor with completed CMMC Level 1 self-assessment and affirmation. Discuss service, maintenance and replacement." path={path} jsonLd={[
      breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Federal HVAC Contracting", path }]),
      { "@context": "https://schema.org", "@type": "Service", "@id": `${BUSINESS.siteUrl}${path}#service`, name: "Federal HVAC contracting", serviceType: "HVAC service, maintenance, installation and replacement", url: `${BUSINESS.siteUrl}${path}`, provider: { "@type": "HVACBusiness", "@id": `${BUSINESS.siteUrl}/#business`, name: BUSINESS.name, url: BUSINESS.siteUrl, telephone: BUSINESS.phone.e164 }, areaServed: ["Mississippi", "Alabama", "Tennessee"].map(name => ({ "@type": "State", name })) },
    ]} />
    <PageHero eyebrow="Federal contractor · Based in Columbus, MS" headline="HVAC support for federal projects" subheadline="Service, preventive maintenance and equipment replacement for facility teams and prime contractors in Mississippi, Alabama and Tennessee.">
      <p className="inline-flex items-center justify-center gap-2 mt-6 rounded-xl border border-sky/40 bg-sky/10 px-5 py-3 font-semibold text-white"><ShieldCheck size={22} aria-hidden="true" />CMMC Level 1 (Self)</p>
      <p className="mt-3 text-sm text-white/75">Self-assessment and affirmation completed</p>
      <div className="flex flex-col sm:flex-row justify-center gap-3 mt-7"><Link to="/contact?service=federal" className="rounded-xl bg-amber px-6 py-3 font-bold text-primary">Discuss a federal project</Link><a href={BUSINESS.phone.href} className="inline-flex justify-center items-center gap-2 rounded-xl border border-white/40 px-6 py-3 text-white font-semibold"><Phone size={18} aria-hidden="true" />{BUSINESS.phone.display}</a></div>
    </PageHero>
    <div className="container mx-auto px-4 py-14 max-w-6xl">
      <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground mb-10"><Link to="/" className="underline">Home</Link> / <span aria-current="page">Federal HVAC Contracting</span></nav>
      <section className="grid lg:grid-cols-[1.4fr_1fr] gap-10 mb-16">
        <div><h2 className="text-3xl font-bold mb-5">A clear starting point for your HVAC scope</h2><p className="text-muted-foreground leading-relaxed mb-4">Weathers Air Conditioning is a federal contractor based in Columbus, Mississippi. We work in Mississippi, Alabama and Tennessee, bringing our heating and cooling services to conversations with government facility teams and prime contractors.</p><p className="text-muted-foreground leading-relaxed">Start with the work you need: the equipment involved, the operating problem, the project location and any scheduling constraints. Our office can discuss fit and availability before you share detailed project documents. Contract requirements, access arrangements and the scope of work need to be confirmed for each opportunity.</p></div>
        <aside className="bg-secondary border border-border rounded-2xl p-7"><Building2 className="text-sky mb-4" aria-hidden="true" /><h2 className="text-xl font-bold mb-3">One point of contact</h2><p className="font-semibold mb-3">{BUSINESS.legalName}</p><p className="text-muted-foreground mb-4">{BUSINESS.address.full}</p><a href={BUSINESS.phone.href} className="block text-sky font-bold text-lg mb-4">{BUSINESS.phone.display}</a><Link to="/contact?service=federal" className="text-sky underline">Request a capabilities conversation</Link></aside>
      </section>
      <section className="mb-16"><h2 className="text-3xl font-bold mb-7">HVAC capabilities to discuss</h2><div className="grid md:grid-cols-3 gap-6">{capabilities.map(item => <div className="rounded-2xl border border-border p-7 bg-card" key={item.title}><h3 className="text-xl font-bold mb-4">{item.title}</h3><p className="text-muted-foreground leading-relaxed">{item.text}</p></div>)}</div><Link to="/services#commercial" className="inline-block mt-6 text-sky underline">Explore commercial HVAC services →</Link></section>
      <section className="rounded-2xl bg-navy text-white p-7 md:p-10 mb-16" aria-labelledby="cmmc-heading"><ShieldCheck className="text-sky mb-4" size={34} aria-hidden="true" /><h2 id="cmmc-heading" className="text-3xl font-bold mb-5">CMMC Level 1: what it means for a project</h2><p className="leading-relaxed text-white/85 mb-5">Weathers has completed its CMMC Level 1 self-assessment and affirmation. Level 1 addresses basic safeguarding of Federal Contract Information (FCI), with annual self-assessment and affirmation requirements.</p><p className="leading-relaxed text-white/85 mb-5">Level 1 is a self-assessment status, not a third-party certification. It does not establish Level 2 status for work involving Controlled Unclassified Information (CUI), and it does not replace the requirements of a particular solicitation. Contact our office to coordinate a review of current status and the requirements applicable to your project.</p><a className="text-sky underline" href="https://business.defense.gov/Cyber/" target="_blank" rel="noopener noreferrer">Read the Department of Defense’s CMMC overview →</a></section>
      <section className="grid md:grid-cols-2 gap-10 mb-16"><div><ClipboardList className="text-sky mb-4" size={32} aria-hidden="true" /><h2 className="text-2xl font-bold mb-4">Prepare a useful first conversation</h2><ul className="list-disc pl-5 space-y-3 text-muted-foreground"><li>A public, high-level description of the work and general project location.</li><li>Whether you need diagnostics, ongoing maintenance or equipment replacement.</li><li>Anticipated timing, occupied-building constraints and allowable shutdown windows.</li><li>The appropriate procurement or facilities point of contact.</li></ul><Link className="inline-block mt-6 text-sky underline font-semibold" to="/blog/federal-hvac-project-scope-checklist">Read the federal HVAC scope checklist →</Link></div><div className="bg-secondary rounded-2xl p-7"><h2 className="text-2xl font-bold mb-4">Start with a public inquiry</h2><p className="text-muted-foreground leading-relaxed mb-4">Use the website form only for public, general inquiries. Do not submit FCI, CUI, access codes, security details or nonpublic facility drawings through the form or in a reply to its automated email.</p><p className="text-muted-foreground leading-relaxed">Call the office to agree on the appropriate information-sharing process before sending project documents. The website form and its email notifications are not presented as an assessed CMMC information system.</p></div></section>
      <section><h2 className="text-3xl font-bold mb-6">Questions from contracting and facility teams</h2><div className="space-y-7"><div><h3 className="text-xl font-bold mb-2">Can a prime contractor contact Weathers about an opportunity?</h3><p className="text-muted-foreground">Yes. Call or submit a public inquiry so the office can discuss scope, location, schedule and project requirements. An inquiry does not confirm bid participation or availability.</p></div><div><h3 className="text-xl font-bold mb-2">Does CMMC Level 1 cover every federal project?</h3><p className="text-muted-foreground">No. The required level and other obligations depend on the solicitation, contract and information involved. Verify those requirements and current applicable status during procurement.</p></div><div><h3 className="text-xl font-bold mb-2">Where does Weathers work?</h3><p className="text-muted-foreground">Weathers works in Mississippi, Alabama and Tennessee from its Columbus office. Contact the office to confirm the location and scope of your proposed project.</p></div></div></section>
    </div>
  </>;
}
